name: flutter_games_collection
description: "Flutter Game Collection. [3.19.5 || 3.22.3]"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flame: ^1.17.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_gradient_colors: ^2.1.1
  ultimate_particle_fx: ^0.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1 # Needed for coordinate handling
  geolocator: ^13.0.1 # To record your travels, you can implement GPS tracking and record the path of your travels on the map.
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/common/
    - assets/images/common/ui/
    - assets/images/emberquest/
    - assets/images/epictd/
    - assets/images/pushpuzzle/
    - assets/images/charactermovement/
    - assets/images/spaceshooter/bullet/
    - assets/images/spaceshooter/player/
    - assets/images/spaceshooter/enemies/
    - assets/images/spaceshooter/powerUps/
    - assets/images/spaceshooter/explosions/
    - assets/images/spaceshooter/parallexBg/

  fonts:
    - family: OldGameFatty
      fonts:
        - asset: assets/fonts/OldGameFatty.ttf
